TYPO3-Documentation/TYPO3CMS-Exceptions

Documentation/Exceptions/1438780511.rst
Previous text was misleading. It is not recommended to use file_reference. This is also deprecated. It is recommend to switch to type 'inline", see https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/Group.html#internal-type
=> Update exception 1438780511

Documentation/Exceptions/1407060572.rst
For the possibilty, an outdated extension template uses old viewhelpers
=> Added Case 5

Documentation/Exceptions/1540246570.rst
Place all three lines in one typoscript codeblock, as it's meant to be in one block.
=> Fix typoscript code block formatting

Documentation/Exceptions/1278155988.rst
Example code was not shown in HTML view, due to wrong Rest code block.
See https://docs.typo3.org/typo3cms/exceptions/master/en-us/Exceptions/1278155988.html
=> [BUGFIX] Replace code block

Documentation/Exceptions/1534710048.rst
This provides additional information on why this error occurs and gives developers information on what version of the extension to use.
=> Improve error description

Documentation/Exceptions/1316104317.rst
See Deprecation: #87550 - Use controller classes when registering plugins/modules
=> Vendor prefix is not required anymore in ExtensionUtility::configurePlugin()

Documentation/Exceptions/1242292003.rst
- Add a note that page is outdated (people may land on the page due to other reasons than the exception and it should not propagate outdated information). Also, link to the related changelog.
- Problem mentioned is not related to Extbase, but related to Fluid. Text was changed slightly to refer to Fluid ViewHelper, not Extbase.
- use term PHPDoc or PHPDoc consistently
=> Fix exception 1242292003

Documentation/Exceptions/1242292003.rst
The configuration setting opcache.load_comments is no longer used in PHP. However, opcache.save_comments still is.
We now mention the PHP version when it was dropped to make it more clear.
> Removed opcache.load_comments configuration directive. Now doc
> comments loading costs nothing and always enabled.
https://prototype.php.net/versions/7.0.0/
=> Refer to PHP version with opcache.load_comments

Documentation/Exceptions/1476107941.rst, Documentation/Settings.cfg
Fix link (link was formatted incorrectly and resulted in it not being rendered correctly).
Use` :doc:` for linking to the changelog: This will also automatically display the title. Previously, there was a "highlight" in the URL but that was not of much value since the part in the docs is easy to find. (Also, now it is not necessary to jump to the changelog, because the "correct" code snippet was added).
Add a "right example" not just a "wrong example" for the configurePlugin part.
Add more descriptive text (as used in the changelog).
Add captions to the code snippets.
Fix problem with yaml code snippet which was not rendered.
Add a link to the DI documentation.
Resolves: #87
Resolves: #88
=> Fix some problems in Exception 1476107941

Documentation/Exceptions/1314778269.rst
When `GeneralUtility::isFirstPartOfStr($localFilePath, $this->absoluteBasePath)` returns true the exception is thrown.
=> Corrected the exception's description.

Documentation/Exceptions/1438780511.rst
between db and folder, there is an additional space added. Before the two words were not rendered correctly inside the documenation
=> Added an additional space

.github/workflows/rendering.yml
The documentation team switched from docker hub to the
GitHub Container Registry as home for the documentation
rendering container. It's not available anymore on the
docker hub.
It has been missed to update the GitHub Action workflow
in this repository to use the new rendering container
home as source to pull the image from. That broke the
rendering of the exception documentation.
This change now uses the new complete image name with
the repository to render the documenation again.
=> [TASK] Use documentation rendering container from ghcr.io

Documentation/Exceptions/1264093642.rst, Documentation/Exceptions/1365799920.rst, Documentation/Exceptions/1476107295.rst
./Documentation/Exceptions/1264093642.rst:49: WARNING: Inline strong start-string without end-string.
./Documentation/Exceptions/1264093642.rst:49: WARNING: Inline emphasis start-string without end-string.
./Documentation/Exceptions/1264093642.rst:57: WARNING: Definition list ends without a blank line; unexpected unindent.
./Documentation/Exceptions/1476107295.rst:171: ERROR: Unexpected indentation.
./Documentation/Exceptions/1476107295.rst:191: WARNING: Title underline too short.
./Documentation/Exceptions/1365799920.rst:25: ERROR: Error in "code-block" directive: maximum 1 argument(s) allowed, 10 supplied.
Additionally, adjust some wordings and formattings as drive-by.
=> [BUGFIX] Correct rendering warnings

.github/workflows/rendering.yml
It seems, the wrong 'docker run' command has been in there from the beginning. However, it was a kind
of mispelling that was simply ignored and didn't
cause harm. So it went unnoticed.
=> Fix rendering.yml

.github/workflows/exception-codes.yml
The correct testsuite to install the application dependencies with composer is `-s composerInstall` because a composer.lock file is used.
In the GitHub Action workflow file the not existing `composerUpdate` has been used, which is wrong.
This change now uses the correct script.
=> [BUGFIX] Use correct command to install dependencies

Build/Scripts/runTests.sh
GitHub Action and others defines a variable "CI" which
can be used to detect a CI environment run. These CI
environments usually don't provide a tty (terminal).
Therefore, we need to respect that environment and remove
the terminal (tty) setting from the docker calls in the
`Build/Scripts/runScript.sh` based on the available CI
env variable.
=> [BUGFIX] Deal with not available tty on CI environments

.github/workflows/exception-codes.yml, Build/app/src/Command/GeneratePagesCommand.php, Build/app/src/Git/CustomGitRepository.php, Build/app/src/Service/FetcherService.php
* Removed additional clean check as unpushed commits are
returned as `has changes` and therefore not feasonable
to check.
* Added additional output regarding the commit creation
for both commands.
* Ensure that the git user name is correctly determined
and not using the email as name value.
* Using `$GITHUB_OUTPUT` output redirection instead of
depreated `::set-output`.
=> [BUGFIX] Ensure that auto-commit is working as GitHub Action

Documentation/Exceptions/1509741911.rst
I searched all the TYPO3-Documentation/ repos for "code-block: " and this was the only occurence I found.
=> [BUGFIX] Replace "code-block: " with double colon

Documentation/Exceptions/1480765571.rst
Please check the syntax.
I copied it from https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Reference/Code/Codeblocks.html, but the code block looks odd in the preview.
Thanks!
=> Add example for including a FlexForm file to a CE

Documentation/Exceptions/1546632293.rst, Documentation/Settings.cfg
./Documentation/Exceptions/1546632293.rst:47: ERROR: Error in "code-block" directive: maximum 1 argument(s) allowed, 29 supplied.
./Documentation/Exceptions/1639819269.rst:16: WARNING: undefined label: t3viewhelper:typo3-fluid-uri-page
=> [BUGFIX] Avoid rendering warnings

Documentation/If-you-encounter-this-exception.rst.txt
This adjusts the part of the exception troubleshooting note to now say:
> [...]
>
> General TYPO3 troubleshooting tips can be found in the section "Troubleshooting" of the menu. You can also ask questions and receive support in the ["TYPO3 Questions" category on talk.typo3.org](https://talk.typo3.org/c/typo3-questions/).
>
> [...]
This decision was made by @mabolek, since we want to get people to post their questions on https://talk.typo3.org primarily, so they are publicly searchable and indexable. This leads to less repeatedly asked questions, as happening in Slack (or other places that rely on real-time communications).
**Side question that I was not able to solve myself:** Is it possible to write in italics inside a link? @mabolek wanted to have text references in italics (e.g. _TYPO3 …
=> Link to talk.typo3.org instead of Slack in Exception note

Documentation/If-you-encounter-this-exception.rst.txt
While accepting the text suggestion in #156 a typo/broken sentence snuck into the paragraph ("...section _Troubleshooting_ section in the menu."). This PR fixes that.
=> Fix typo in troubleshooting notice

Documentation/Exceptions/1666513645.rst
There is no setup on some pages. 
hasSetup must be called.
=> call hasSetup before getSetupArray

Documentation/Exceptions/1588095936.rst
Based on information found here:
https://stackoverflow.com/questions/63869637/unable-to-login-to-new-typo3-10-4-8
adding:
```
'reverseProxyIP' => '*',
'reverseProxySSL' => '*',
```
to my typo3conf/system/settings.php file solved my problem of 
"Invalid referrer for /main"
=> Handling of reverseproxy problems
