Documentation/Exceptions/1297759968.rst
Tried to describe the solution as general as possible.
=> Added another error message

Documentation/Exceptions/1476107941.rst
Explain that the exception 1476107941 might be caused by a not properly configured Services.yaml.
=> [TASK] Add possible solution for exception 1476107941

Documentation/Exceptions/1313855175.rst
Updated the example code for configuring a plugin to match the current api.
=> Updated example code

Documentation/Exceptions/1313855175.rst
Added an info box to highlight that switchable controller actions are deprecated
=> Added info box

Documentation/Exceptions/1502987245.rst
https://github.com/TYPO3-Documentation/TYPO3CMS-Exceptions/blob/master/Documentation/Exceptions/1255069597.rst
=> Add TYPO3 Exception 1502987245 like 1255069597

Documentation/Exceptions/1294587217.rst, Documentation/Exceptions/1389265726.rst, Documentation/Exceptions/1581862822.rst
See TYPO3-Documentation/T3DocTeam#166 for details.
=> [TASK] Unify placeholder syntax

Documentation/Settings.cfg
version and intersphinx mapping
=> Change from master to main

Documentation/Settings.cfg
Is necessary for "Edit on GitHub" to work
=> Change github_branch to main in Settings.cfg

Documentation/Exceptions/1166633721.rst, Documentation/Exceptions/1217839467.rst, Documentation/Exceptions/1218547409.rst, Documentation/Exceptions/1232985914.rst, Documentation/Exceptions/1237823695.rst, Documentation/Exceptions/1242292003.rst, Documentation/Exceptions/1247602160.rst, Documentation/Exceptions/1251315967.rst, Documentation/Exceptions/1270853884.rst, Documentation/Exceptions/1278155988.rst, Documentation/Exceptions/1289386765.rst, Documentation/Exceptions/1313855175.rst, Documentation/Exceptions/1404068038.rst, Documentation/Exceptions/1481380393.rst, Documentation/Exceptions/1482394401.rst, Documentation/Exceptions/Index.rst
See TYPO3-Documentation/T3DocTeam#174 for details.
=> [TASK] Update hints of Extension Builder

.github/workflows/rendering.yml, CONTRIBUTING.rst, Documentation/Exceptions/1278450972.rst, Documentation/Exceptions/1360403545.rst, Documentation/Exceptions/1365429656.rst, Documentation/Exceptions/1375889830.rst, Documentation/Exceptions/1392409507.rst, Documentation/Exceptions/1438594406.rst, Documentation/Exceptions/1476107941.rst, Documentation/Exceptions/1581862822.rst, Documentation/Index.rst, README.rst
=> [TASK] Switch from master to main

Documentation/Exceptions/1203699034.rst
Solution for old $TYPO3_CONF_VARS to replace with $GLOBALS['TYPO3_CONF_VARS']
=> Exception 1203699034.rst

Documentation/Exceptions/1476107295.rst
Based on the **Praxiswissen CMS 10 LTS** book by Meyer, Helmich et al.
=> Added another example

Documentation/Exceptions/1588095935.rst
- The error is not limited to minor updates in version 9
- Make it clear that this is a security feature
- Explain a solution right away and dont link to the next doc again
=> Be more verbose in backend.enforceReferrer error

Documentation/Exceptions/1616175867.rst
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Exceptions/issues/96
=> [BUGFIX] Correct link to changelog

Documentation/Exceptions/1381512761.rst
Relates: https://forge.typo3.org/issues/99401
=> Extend TYPO3 Exception 1381512761 for -1 VersionState

Documentation/Exceptions/1237823699.rst
Add issue + solution of form framework exception about error handlers.
=> Add exception of form framework

Documentation/Exceptions/1588095935.rst
Additionally:
- Use the correct code block language
- Adjust path to backend module
=> [BUGFIX] Display PHP namespace correctly

Documentation/Exceptions/1316104317.rst
From slack discussion https://typo3.slack.com/archives/C025BQLFA/p1698352097737589
=> Update Exception 1316104317 with additional reason and solution

.github/workflows/exception-codes.yml, .github/workflows/rendering.yml, Build/Scripts/runTests.sh
- [BUGFIX] Add `p` to allowed getops in `runTests.sh`
- [TASK] Allow manual execution of both workflow files
=> [TASK] Exception page generation (workflow definition)

Documentation/Exceptions/1257246929.rst
Document "format" being a reserved keyword
=> [TASK] Document reserved extbase keyword "format"

Documentation/Exceptions/1540246570.rst
Follow up for https://github.com/TYPO3-Documentation/TYPO3CMS-Exceptions/pull/153
=> [BUGFIX] Use TypoScript from file

.github/workflows/test-documentation.yml, Documentation/Exceptions/1257246929.rst, Documentation/Exceptions/1705656657.rst, Makefile
=> [TASK] Add a testing workflow

Documentation/Exceptions/1616175867.rst
I have tested it. When I log in with the Install Tool, then I can try the login again despite of too many trials.
=> add solution Install Tool
